example.map:
  order1.area:
    coordinates:
      - -50,50
      - 0,0
    activities:
      - example.agenda::order

  pickup1.area:
    coordinates:
      - -50,0
      - 0,-20
    activities:
      - example.agenda::pickup
    link: order1.area|example.agenda::order

