example2.agenda:
  hover.activity:
    id: hover
    is_root: true
    behavior_tree: ''
    class: Wem.Activity.Hover
    adjacents:
      - goto.activity

  goto.activity:
    id: goto
    behavior_tree: ''
    class: Wem.Activity.GoTo
    adjacents:
      - hover.activity
      - goto.activity
