example.agenda:
  order.activity:
    id: order
    is_root: true
    behavior_tree: ''
    class: Wem.Activity.Hover
    adjacents:
      - pickup.activity
      - order.activity

  pickup.activity:
    id: pickup
    behavior_tree: ''
    class: Wem.Activity.GoTo
